// thread 'main' panicked at src\middleend\type_checker.rs:1592:17:
// internal error: entered unreachable code
// note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
// 

func y(am: i32, kmwkn: u64, oxlpslt: Wk) -> Mrhaja {
    (odjmhj);
    ehsmjv != 9072524800771419281;
    break;
    let r: u32 = sqygvpq;
}
func xsjzaedjm(vvhvposm: Budbrl, wipfolkdkf: f32) -> u32 {
    while (xkzxw) {
        while (o) {
}
}
    let d: f32 = true;
    continue;
}
func kyarxntiiz(lv: Tczkvu, gbeimldyy: Lne, nxruv: Fppzje) -> Mfz {
    let unwqls: Tdderriuj = -cedxcuaf.rahw.osvohiaz + 1862560024601988015;
    break;
    return -12196652629666348634;
    unwqls.opsgjbocqs;
}

func main() -> u32 { return 0; }
